### PR TITLE
37 cicd setup

### PR DESCRIPTION
**Pull request by jojayama**
I did steps 3 and 4, so I'm trying to push that to main. Other that, since we can only try to deploy from main, I'm attempting to push fixes to main to get a successful deploy. Please look at the code and the pictures below for review, and let me know if there's anything I should fix/try.

image

image

### CODE REVIEW

**Comment by samikshakarimbil** [comment]
Looks good, thanks!

**Comment by charm-13** [comment]
code looks good to me, just make sure to look at the checks before merging as some of them seemed to fail.

**Review by charm-13 — COMMENTED** [review]
code looks good to me, just make sure to look at the checks before merging as some of them seemed to fail.

**Review by samikshakarimbil — COMMENTED** [review]
Looks great, thanks!

**Comment by jojayama** [comment]
@charm-13 Yeah thank you! I'm definitely working on trying to pass the checks right now. I realized that I can push it to this issue to see if it'll pass the checks so I'll merge the code to main after passing all the checks and requesting you guys to review again.

**Comment by jojayama** [comment]
Okay! I officially got all of the checks to pass! Yayy!! Since @j-schm worked on the first part, did you want to take a look at the changes I made? Thanks!

**Comment by j-schm** [comment]
the most recent code looks good, recent builds also running significantly faster -- great! i think it should be alright to merge to main

**Comment by jojayama** [comment]
> the most recent code looks good, recent builds also running significantly faster -- great! i think it should be alright to merge to main

okay thank you! I'll merge it right now!

**Pull request merged**
