### PR TITLE
Calendar - Feelings Tracking Mechanism

### PR DESCRIPTION
**Pull request by charm-13**
Added a feelings tracking mechanism. 
Still working on events

### CODE REVIEW

**Comment by jojayama** [comment]
Hey @charm-13! Do you think you could put a screenshot of what that looks like on our calendar now? Also, would we need to do anything with the backend to connect the emotions to the specific user?

**Review by jojayama — COMMENTED** [review]
Hey @charm-13! Do you think you could put a screenshot of what that looks like on our calendar now? Also, would we need to do anything with the backend to connect the emotions to the specific user?

**Comment by charm-13** [comment]
> Hey @charm-13! Do you think you could put a screenshot of what that looks like on our calendar now? Also, would we need to do anything with the backend to connect the emotions to the specific user?

The calendar essentially looks the same. The only real difference is when you click on a date a prompt will appear asking for an emotion for the day. 
I'm not entirely sure how to connect it to the backend, but I can look into that over the next couple of days

**Review by samikshakarimbil — COMMENTED** [review]
Great job!

**Comment by j-schm** [comment]
azure static web app checks failed, should consider checking. looks good on the code tho !

**Comment by jojayama** [comment]
to fix it, try to run "npx prettier --write ." in the console and see if that works!

**Comment by charm-13** [comment]
> to fix it, try to run "npx prettier --write ." in the console and see if that works!

thanks! i'll try this tomorrow morning

**Comment by charm-13** [comment]
all checks pass now, merging

**Pull request merged**
