### PR TITLE
100 access control implementation

### PR DESCRIPTION
**Pull request by jojayama**
I added the access control... so there's a url on the top of the website that says something about just checking out the site. if a user clicks that, they can't see any reminders or goal, since the access is denied... when a user creates an account and logs in, they get a token that will let them see their reminders and goals and stuff

New Login:
image

What happens in the console when you click the new url in login:
image

### CODE REVIEW

**Review by charm-13 — APPROVED** [review]
looks good to me, go ahead and merge

**Review by samikshakarimbil — COMMENTED** [review]
Great job getting this done so quick, it looks good!

**Comment by j-schm** [comment]
it looks good, glad all the deployment and checks are working now! thanks!

**Review by j-schm — APPROVED** [review]
code looks good, glad all the deployment and checks are working now. thanks!

**Pull request merged**
