### PR TITLE
110 populate diary entry viewing page

### PR DESCRIPTION
**Pull request by jojayama**
I was able to get it so the user can look at a specific diary entry by clicking the title. LET ME KNOW: if you think I should get rid of the "Edit" feature (since we're short on time) or if you want me to put a delete button (that should be quick). Also @samikshakarimbil, if you would like please fix the return button under the edit button if we're keeping the edit button.

image
image

### CODE REVIEW

**Review by charm-13 — CHANGES_REQUESTED** [review]
remove the edit (short time), add a delete (only if it's simple enough)
after this change it's good to go

**Review by samikshakarimbil — COMMENTED** [review]
Looks good! I'll leave editing and deleting up to you, just do it if there's enough time for you. I'll make the frontend fix regardless so that it's good to go either way.

**Comment by jojayama** [comment]
image
^^ delete button on single entry page
image
^^ entire diary entry viewing page

**Comment by charm-13** [comment]
yay looks BEAUTIFUL!! ty jodi
go merge :)

**Comment by jojayama** [comment]
> yay looks BEAUTIFUL!! ty jodi go merge :)

yayyy thank you!

**Pull request merged**
