### PR TITLE
Diary frontend

### PR DESCRIPTION
**Pull request by samikshakarimbil**
I made the frontend for making a new diary entry, also for viewing diary entries in general.
Here's the screenshot for a new entry:
pr ss
image

### CODE REVIEW

**Review by charm-13 — APPROVED** [review]
code looks good!
what does typing in the Title and ... areas look like?

**Review by jojayama — COMMENTED** [review]
This looks great Sam! Thank you for making it! I’ll route it after you merge it :)

**Comment by samikshakarimbil** [comment]
> code looks good! what does typing in the Title and ... areas look like?

I edited the PR to include a screenshot of this!

**Comment by jojayama** [comment]
Also, is there a page to view all of the entries?

**Comment by samikshakarimbil** [comment]
> Also, is there a page to view all of the entries?

Yup its empty but heres a screenshot
image

**Comment by jojayama** [comment]
> > Also, is there a page to view all of the entries?
> 
> Yup its empty but heres a screenshot image

This looks AMAZING! Thank you!!

**Comment by j-schm** [comment]
code looks good. are the conflicts "that must be resolved" going to be an issue when merged? if now, should be fine merging into main

**Pull request merged**
